modLoader = "javafml"
loaderVersion = "[0,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${displayName}"
authors = "Ran"
description = '''
Hewwo >_<
'''
logoFile = "icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"