name: build
on: [pull_request, push]

jobs:
  build-1_19_3:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build 1.19.3
        run: ./gradlew assemble -PmcVer="1.19.3"
      - name: capture build artifacts
        if: ${{ github.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Merged/

  build-1_19_2:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build 1.19.2
        run: ./gradlew assemble -PmcVer="1.19.2"
      - name: capture build artifacts
        if: ${{ github.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Merged/

  build-1_18_2:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build 1.18.2
        run: ./gradlew assemble -PmcVer="1.18.2"
      - name: capture build artifacts
        if: ${{ github.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Merged/

  build-1_16_5:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build 1.16.5
        run: ./gradlew assemble -PmcVer="1.16.5"
      - name: capture build artifacts
        if: ${{ github.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Merged/
